name: "Build Image Action"
description: "generic action for building job"
inputs:
  docker-image-name:
    required: true
    default: "sample_image"
  docker-image-tag:
    required: true
    default: "latest"
  docker-file-path:
    required: true
    default: ""
  docker-file-name:
    required: true
    default: "Dockerfile"
outputs:
  image-tar-name: 
    value: ${{ steps.step1.outputs.image-tar-name }}
runs:
  using: "composite"
  steps:
    - id: step1
      run: |
        cd "${{ inputs.docker-file-path }}"
        docker build -t ${{ inputs.docker-image-name }}:${{ inputs.docker-image-tag }} -f ${{ inputs.docker-file-name }} .
        docker save -o image1.tar ${{ inputs.docker-image-name }}:${{ inputs.docker-image-tag }}
        touch image1.tar
        pwd; ls -l
        echo "image-tar-name=$(realpath ./image1.tar)">> $GITHUB_OUTPUT
      shell: bash
    - run: pwd; ls -l
      shell: bash
