name: Workflow1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ekkagra/room_manage
          path: room_manage
      - uses: actions/checkout@v3
        with:
          path: test
      - run: |
          tree
      - id: build-step
        uses: ./test/github/actions/build_image_action
        with:
          docker-image-name: 'jarvis'
          docker-image-tag: 'v1.0.0'
          docker-file-path: './room_manage/docker'
          docker-file_name: 'Dockerfile'
      - uses: actions/upload-artifact@v3
        with:
          name: image_artifact
          path: $$ {{ steps.build-step.outputs.image-tar-name }}
      - run: |
          git log --graph --oneline > log.txt
      - run: |
          tar -cvf log.tar log.txt
      - run: |
          docker -h
          docker version
      - uses: actions/upload-artifact@v3
        with:
          name: log_artifact
          path: log.tar
