name: Workflow1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - run: pwd; ls -l
      - uses: actions/checkout@v3
        with:
          repository: ekkagra/room_manage
          path: room_manage
      - run: pwd; ls -l
      - uses: actions/checkout@v3
        with:
          path: test
      - run: pwd; ls -l
      - run: find .
      - id: build-step
        uses: ./test/.github/actions/build_image_action
        with:
          docker-image-name: 'jarvis'
          docker-image-tag: 'v1.0.0'
          docker-file-path: './room_manage/docker'
          docker-file-name: 'Dockerfile'
      - run: pwd
      - run: ls -l
      - uses: actions/upload-artifact@v3
        with:
          name: image_artifact
          path: ${{ steps.build-step.outputs.image-tar-name }}
